{% set name = "yaqd-thorlabs" %}
{% set version = "2021.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 96b140fed38ee7a74ed28ed4b0d9708b4d3b970c1f50d752446a6533bf66c183

build:
  number: 0
  noarch: python
  entry_points:
    - yaqd-thorlabs-k10cr1 = yaqd_thorlabs._thorlabs_k10cr1:ThorlabsK10CR1.main
    - yaqd-thorlabs-kdc101 = yaqd_thorlabs._thorlabs_kdc101:ThorlabsKDC101.main
    - yaqd-thorlabs-lts150 = yaqd_thorlabs._thorlabs_lts150:ThorlabsLTS150.main
    - yaqd-thorlabs-lts300 = yaqd_thorlabs._thorlabs_lts300:ThorlabsLTS300.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - flit
    - thorlabs-apt-protocol
    - pyserial
    - yaqd-core >=2020.06.3
  run:
    - python >=3.7
    - thorlabs-apt-protocol
    - pyserial
    - yaqd-core >=2020.06.3

test:
  imports:
    - yaqd_thorlabs
  commands:
    - pip check
    - yaqd-thorlabs-k10cr1 --help
    - yaqd-thorlabs-kdc101 --help
    - yaqd-thorlabs-lts150 --help
    - yaqd-thorlabs-lts300 --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: yaq daemons for thorlabs hardware
  dev_url: https://gitlab.com/yaq/yaqd-thorlabs
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
