{% set name = "yaqd-thorlabs" %}
{% set version = "2022.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eea5ad0cdde1605d3cd5eb4c2354b7bf8a1b9f55867eb0b0857cb1dfe3003d73

build:
  number: 0
  noarch: python
  entry_points:
    - yaqd-thorlabs-k10cr1 = yaqd_thorlabs._thorlabs_k10cr1:ThorlabsK10CR1.main
    - yaqd-thorlabs-kdc101 = yaqd_thorlabs._thorlabs_kdc101:ThorlabsKDC101.main
    - yaqd-thorlabs-kst101 = yaqd_thorlabs._thorlabs_kst101:ThorlabsKST101.main
    - yaqd-thorlabs-lts150 = yaqd_thorlabs._thorlabs_lts150:ThorlabsLTS150.main
    - yaqd-thorlabs-lts300 = yaqd_thorlabs._thorlabs_lts300:ThorlabsLTS300.main
    - yaqd-thorlabs-bsc201 = yaqd_thorlabs._thorlabs_bsc201:ThorlabsBSC201.main
    - yaqd-thorlabs-bsc203 = yaqd_thorlabs._thorlabs_bsc203:ThorlabsBSC203.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - flit
    - thorlabs-apt-protocol
    - pyserial
    - yaqd-core >=2020.06.3
  run:
    - python >=3.7
    - thorlabs-apt-protocol
    - pyserial
    - yaqd-core >=2020.06.3

test:
  imports:
    - yaqd_thorlabs
  commands:
    - pip check
    - yaqd-thorlabs-k10cr1 --help
    - yaqd-thorlabs-kdc101 --help
    - yaqd-thorlabs-lts150 --help
    - yaqd-thorlabs-lts300 --help
    - yaqd-thorlabs-kst101 --help
    - yaqd-thorlabs-bsc201 --help
    - yaqd-thorlabs-bsc203 --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: yaq daemons for thorlabs hardware
  dev_url: https://gitlab.com/yaq/yaqd-thorlabs
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
